// <auto-generated />
using System;
using FamilyTreeData.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyTreeData.Migrations
{
    [DbContext(typeof(FamilyTreeDbContext))]
    [Migration("20230413155246_InitalCreate")]
    partial class InitalCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("FamilyTreeLib.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Dob")
                        .HasColumnType("DATETIME")
                        .HasColumnName("date_of_birth");

                    b.Property<int>("FatherId")
                        .HasMaxLength(20)
                        .HasColumnType("INTEGER")
                        .HasColumnName("father_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MotherName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("mother_name");

                    b.Property<string>("WifeImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("WifeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("wife_name");

                    b.HasKey("Id");

                    b.HasIndex("FatherId");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("FamilyTreeLib.Entities.Person", b =>
                {
                    b.HasOne("FamilyTreeLib.Entities.Person", "Father")
                        .WithMany("Children")
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Father");
                });

            modelBuilder.Entity("FamilyTreeLib.Entities.Person", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
